import os
import json
from dotenv import load_dotenv

load_dotenv()

USE_GEMINI = False

if USE_GEMINI:
    from google import genai
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


def generate_notes(topic: str, level: str = "intermediate", style: str = "structured") -> str:
    if USE_GEMINI:
        prompt = f"""Generate comprehensive study notes on the topic: "{topic}"
Level: {level}
Style: {style}

Format the notes like this:
📚 Study Notes: {topic}

1. Introduction
   - Brief overview of the topic

2. Key Concepts
   - Main ideas and definitions

3. Important Points
   - Bullet points of must-know information

4. Examples
   - Real-world examples

5. Summary
   - Quick revision points

Make it clear, easy to understand, and useful for exam preparation."""

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt
        )
        return response.text

    # Fake notes (used when quota is exhausted)
    return f"""📚 Study Notes: {topic.upper()}
Level: {level.capitalize()} | Style: {style.capitalize()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. 📖 Introduction
   • {topic} is a fundamental concept in computer science.
   • It is widely used in real-world applications.
   • Understanding {topic} is essential for exams and interviews.

2. 🔑 Key Concepts
   • Definition: {topic} refers to the structured approach of managing data.
   • Core principles and components of {topic}
   • How {topic} works internally step by step

3. ⭐ Important Points
   • {topic} improves efficiency and performance
   • It is used in databases, operating systems, and networks
   • Key terms: normalization, optimization, structure

4. 💡 Examples
   • Real-world example: {topic} is used in banking systems
   • Practical use case: {topic} helps in managing large datasets
   • Example in code: SQL queries use {topic} concepts

5. 📝 Summary
   • {topic} is important for building strong technical foundations
   • Regular revision of {topic} improves exam performance
   • Practice problems related to {topic} for better understanding

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✨ Generated by NoteForge AI"""


def generate_flashcards(topic: str) -> list:
    if USE_GEMINI:
        prompt = f"""Generate 5 flashcards for the topic: "{topic}"
Return ONLY a JSON array, nothing else, no markdown backticks:
[
  {{"question": "What is ...?", "answer": "..."}},
  {{"question": "Define ...?", "answer": "..."}},
  {{"question": "What is the use of ...?", "answer": "..."}},
  {{"question": "Give an example of ...?", "answer": "..."}},
  {{"question": "Why is ... important?", "answer": "..."}}
]"""
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt
        )
        text = response.text.strip()
        text = text.replace("```json", "").replace("```", "").strip()
        return json.loads(text)

    # Fake flashcards
    return [
        {"question": f"What is {topic}?", "answer": f"{topic} is a fundamental concept used in computer science and real-world applications."},
        {"question": f"What are the key components of {topic}?", "answer": f"The key components of {topic} include structure, organization, and efficient management of data."},
        {"question": f"Give a real-world example of {topic}.", "answer": f"{topic} is used in banking systems, e-commerce platforms, and data management applications."},
        {"question": f"Why is {topic} important?", "answer": f"{topic} is important because it improves performance, efficiency, and helps in solving complex problems."},
        {"question": f"What are the advantages of {topic}?", "answer": f"Advantages of {topic} include better organization, faster access, reduced redundancy, and improved reliability."},
    ]